### ISSUE TITLE
Question: next-intl support?

### ISSUE THREAD

**Issue by noahbald** [nabekou29/js-i18n.nvim#6]
Hello, just found this through the latest dotfyle.com newsletter and it looks really useful.

I’m using a very similar library, next-intl, which looks very similar to i18next.

I don’t mean to get in the way of your awesome work so far, but curious if this was something you were looking into? :)

**Comment by nabekou29** [comment]
@noahbald 
Thank you for your interest in my plugin.

I tested it with [this example](https://github.com/amannn/next-intl/tree/main/examples/example-app-router) and found that by making some changes to the plugin's configuration and implementation, it can be used to some extent with next-intl.

The plugin configuration should be as follows.

```lua
opts = {
  translation_source = { "**/messages/*.json" },
  detect_language = function(path)
    return path:match("([^/]+)%.json$")
  end,
},
```

As with i18next, passing a namespace to useTranslations is not supported.

Therefore, you can rewrite it as shown in the image below to display virtual text.

| `src/app/[locale]/page.tsx` (Original) | `src/app/[locale]/page.tsx` (Edited) |
|--------|--------|
| <image width="480px" src="https://github.com/user-attachments/assets/95a6bbe8-95a2-4bf1-8e7c-4531cc2633fe"> | <image width="480px" src="https://github.com/user-attachments/assets/5e9b9d12-3c28-49fb-bfb6-982e9aa76057"> | 

If you need any specific features, please let me know.

**Comment by baldwinn-anz** [comment]
Thanks, this seems to only work if the full translation path is passed to `t` though
```ts
// Works
const t = useTranslation()
t('IndexPage.title')

// Doesn't work
const t = useTranslation('IndexPage')
t('title')
```

**Comment by noahbald** [comment]
Thanks, this seems to only work if the full translation path is passed to `t` though
```ts
// Works
const t = useTranslation()
t('IndexPage.title')

// Doesn't work
const t = useTranslation('IndexPage')
t('title')
```

**Comment by noahbald** [comment]
> If you need any specific features, please let me know.

Were there any plans to allow next-intl's namespacing?

```ts
const t = useTranslation('my.namespace')
t('value') // my.namespace.value
```

> you can rewrite it as shown

I won't have the power to do this across my organisation's project

**Comment by nabekou29** [comment]
> Were there any plans to allow next-intl's namespacing?

Once the implementation of priority features is complete, I would like to support namespaces as well.

In order to support namespace features, the plugin requires a higher level of code analysis. So it may take some time to implement.

**Comment by nabekou29** [comment]
@noahbald 
Hello,
I’ve improved support for next-intl and also added keyPrefix support.
Please update to the latest version and give it a try.  If you encounter any bugs or have further feedback, please report it.

**Comment by noahbald** [comment]
Sorry for late response, but this is working well. Thanks for all the effort!
