### ISSUE TITLE
Add diagnostics messages on missing translations

### ISSUE THREAD

**Issue by fragov** [nabekou29/js-i18n.nvim#7]
Thank you for the fantastic plugin! I have been waiting for something like this for since long.

Would it be possible to add diagnostics messages, when a translation for some key is missed in one/several languages?

**Comment by nabekou29** [comment]
@fragov 
Thank you for your question.

Unfortunately, at the moment, it is not possible to display diagnostic messages.
However, I also wanted that feature a littel, so I will work on adding it in a future update.

**Comment by nabekou29** [comment]
This feature was released in v0.3.0, so I will close this issue.
